spring.application.name=redcarga
spring.profiles.active=dev

# Actuator y defaults seguros
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
spring.jpa.open-in-view=false
server.forward-headers-strategy=framework

# Flyway ON por defecto (controla por env)
spring.flyway.enabled=true

# WS por defecto (en prod lo restringes por env)
redcarga.ws.heartbeat.server-ms=10000
redcarga.ws.heartbeat.client-ms=10000
redcarga.ws.message-size.max-bytes=65536

# Niveles de log que no filtran secretos
logging.level.org.springframework.web.socket=INFO
logging.level.org.springframework.messaging=INFO
logging.level.com.app.redcarga=INFO
