-- =============================================
-- 1. Fix guides.guide_id -> identity
-- =============================================
ALTER TABLE deals.guides
    ALTER COLUMN guide_id
    ADD GENERATED BY DEFAULT AS IDENTITY;

-- (Opcional: si existía una secuencia vieja)
-- DROP SEQUENCE IF EXISTS deals.guides_guide_id_seq;


-- =============================================
-- 2. checklist_instance_item: preparar assignment_id
-- =============================================

-- 2.1 Asegurar que assignment_id permita NULL antes de borrar
ALTER TABLE deals.checklist_instance_item
    ALTER COLUMN assignment_id DROP NOT NULL;

-- 2.2 Drop de foreign keys si existen (nombres típicos generados)
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'checklist_instance_item_assignment_id_fkey'
    ) THEN
        ALTER TABLE deals.checklist_instance_item
            DROP CONSTRAINT checklist_instance_item_assignment_id_fkey;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'checklist_instance_item_payment_id_fkey'
    ) THEN
        ALTER TABLE deals.checklist_instance_item
            DROP CONSTRAINT checklist_instance_item_payment_id_fkey;
    END IF;
END $$;


-- =============================================
-- 3. Eliminar columnas
-- =============================================
ALTER TABLE deals.checklist_instance_item
    DROP COLUMN IF EXISTS document_id;

ALTER TABLE deals.checklist_instance_item
    DROP COLUMN IF EXISTS payment_id;

ALTER TABLE deals.checklist_instance_item
    DROP COLUMN IF EXISTS assignment_id;
