

-- =====================================================
-- BC: DEALS — Esquema, tablas y llaves
-- =====================================================

CREATE SCHEMA IF NOT EXISTS deals;


-- =========================================
-- CATÁLOGOS (solo estructuras)
-- =========================================
CREATE TABLE IF NOT EXISTS deals.catalog_quote_state (
  code VARCHAR(32) PRIMARY KEY,        -- PENDIENTE|TRATO|EN_ESPERA|ACEPTADA|RECHAZADA|CERRADA|CERRADA_NO_ADJ
  name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS deals.catalog_change_kind    (code VARCHAR(16) PRIMARY KEY);
CREATE TABLE IF NOT EXISTS deals.catalog_change_status  (code VARCHAR(16) PRIMARY KEY);
CREATE TABLE IF NOT EXISTS deals.catalog_chat_type      (code VARCHAR(16) PRIMARY KEY);
CREATE TABLE IF NOT EXISTS deals.catalog_chat_subtype   (code VARCHAR(32) PRIMARY KEY);
CREATE TABLE IF NOT EXISTS deals.catalog_actor_role     (code VARCHAR(16) PRIMARY KEY);
CREATE TABLE IF NOT EXISTS deals.catalog_checklist_kind (code VARCHAR(16) PRIMARY KEY);
CREATE TABLE IF NOT EXISTS deals.catalog_checklist_status (code VARCHAR(16) PRIMARY KEY);
CREATE TABLE IF NOT EXISTS deals.catalog_payment_status (code VARCHAR(16) PRIMARY KEY);

-- =========================================
-- QUOTES (Cotización) + ITEMS
-- =========================================
CREATE TABLE IF NOT EXISTS deals.quote (
  quote_id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id      INT NOT NULL,                                         -- FK lógico a requests.request(id)
  company_id     INT NOT NULL,
  state_code      VARCHAR(32) NOT NULL REFERENCES deals.catalog_quote_state(code),
  total_amount    NUMERIC(18,2) NOT NULL,
  currency_code   VARCHAR(3) NOT NULL DEFAULT 'PEN',                    -- ISO-4217: PEN, USD, ...
  version         INT NOT NULL DEFAULT 0,
  created_by      INT NOT NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_quote_request   ON deals.quote(request_id);
CREATE INDEX IF NOT EXISTS ix_quote_company  ON deals.quote(company_id);

-- ÚNICA ACEPTADA POR SOLICITUD (índice parcial por estado):
CREATE UNIQUE INDEX IF NOT EXISTS ux_quote_one_accepted_per_request
  ON deals.quote (request_id)
  WHERE state_code = 'ACEPTADA';

CREATE TABLE IF NOT EXISTS deals.quote_item (
  quote_item_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quote_id        INT NOT NULL REFERENCES deals.quote(quote_id) ON DELETE CASCADE,
  request_item_id INT NOT NULL,                         -- FK a requests.request_item(id)
  qty             NUMERIC(18,3) NOT NULL CHECK (qty > 0),
  version         INT NOT NULL DEFAULT 0,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (quote_id, request_item_id)
);
CREATE INDEX IF NOT EXISTS ix_quote_item_quote ON deals.quote_item(quote_id);


-- =========================================
-- CAMBIOS (cabecera)
-- =========================================
CREATE TABLE IF NOT EXISTS deals.change (
                                            change_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            quote_id     INT NOT NULL REFERENCES deals.quote(quote_id) ON DELETE CASCADE,
    kind_code    VARCHAR(16) NOT NULL REFERENCES deals.catalog_change_kind(code),     -- LIBRE | PROPUESTA
    status_code  VARCHAR(16) NOT NULL REFERENCES deals.catalog_change_status(code),   -- APLICADO | PENDIENTE | RECHAZADO
    created_by   INT NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
    );
CREATE INDEX IF NOT EXISTS ix_change_quote ON deals.change(quote_id, created_at);

-- =========================================
-- DETALLE DEL CAMBIO (solo lo que cambió)
-- Tipos permitidos:
--   PRICE_TOTAL    -> cambia deals.quote.total_amount         (sin target)
--   QTY            -> cambia deals.quote_item.qty             (target = quote_item)
--   ITEM_ADD       -> agrega request_item a la cotización     (target = request_item)
--   ITEM_REMOVE    -> quita un quote_item de la cotización    (target = quote_item)
-- =========================================
CREATE TABLE IF NOT EXISTS deals.change_item (
    change_item_id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    change_id          INT NOT NULL REFERENCES deals.change(change_id) ON DELETE CASCADE,
    field_code         VARCHAR(32) NOT NULL,     -- PRICE_TOTAL|QTY|ITEM_ADD|ITEM_REMOVE
-- targets tipados (evitamos un polimórfico confuso):
    target_quote_item_id   INT REFERENCES deals.quote_item(quote_item_id),
    target_request_item_id INT, -- FK lógica a requests.request_item(id)
    old_value          TEXT,
    new_value          TEXT,
    -- Solo se permiten estos tipos:
    CONSTRAINT ck_change_item_field
    CHECK (field_code IN ('PRICE_TOTAL','QTY','ITEM_ADD','ITEM_REMOVE')),
    -- Reglas de target según el tipo:
    CONSTRAINT ck_change_item_target
    CHECK (
(field_code = 'PRICE_TOTAL'  AND target_quote_item_id IS NULL AND target_request_item_id IS NULL) OR
(field_code = 'QTY'          AND target_quote_item_id IS NOT NULL AND target_request_item_id IS NULL) OR
(field_code = 'ITEM_REMOVE'  AND target_quote_item_id IS NOT NULL AND target_request_item_id IS NULL) OR
(field_code = 'ITEM_ADD'     AND target_request_item_id IS NOT NULL AND target_quote_item_id IS NULL)
    )
    );
CREATE INDEX IF NOT EXISTS ix_change_item_change ON deals.change_item(change_id);

-- =========================================
-- ACEPTACIÓN con doble confirmación (handshake de estado)
-- =========================================
CREATE TABLE IF NOT EXISTS deals.acceptance_proposal (
    acceptance_id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quote_id          INT NOT NULL REFERENCES deals.quote(quote_id) ON DELETE CASCADE,
    status_code       VARCHAR(16) NOT NULL CHECK (status_code IN ('PENDIENTE','CONFIRMADA','RECHAZADA')),
    initiator_user_id INT NOT NULL,
    resolver_user_id  INT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    resolved_at       TIMESTAMPTZ,
    idempotency_key   VARCHAR(64) UNIQUE
    );
-- A lo sumo 1 propuesta PENDIENTE por cotización:
CREATE UNIQUE INDEX IF NOT EXISTS ux_acceptance_pending_once
    ON deals.acceptance_proposal(quote_id)
    WHERE status_code = 'PENDIENTE';


-- =========================================
-- CHAT (mensajes)
-- (colocamos la FK a acceptance_proposal ya creada)
-- =========================================
CREATE TABLE IF NOT EXISTS deals.chat_message (
    chat_message_id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Conversación = la propia cotización
    quote_id             INT NOT NULL REFERENCES deals.quote(quote_id) ON DELETE CASCADE,
    -- USER o SYSTEM
    type_code            VARCHAR(16) NOT NULL REFERENCES deals.catalog_chat_type(code),
    -- Subtipo solo cuando es SYSTEM (p. ej. CHANGE_APPLIED, PAYMENT_CONFIRMED, etc.)
    system_subtype_code  VARCHAR(32) REFERENCES deals.catalog_chat_subtype(code),
    -- Contenido mínimo
    body                 TEXT NOT NULL DEFAULT '',              -- texto del mensaje / descripción breve del evento
-- Para enlazar eventos del sistema a entidades conocidas (opcionales; usa los que necesites)
    ref_change_id        INT REFERENCES deals.change(change_id),
    ref_acceptance_id    INT REFERENCES deals.acceptance_proposal(acceptance_id),
    -- NUEVO: contenido de usuario (texto/imagen)
    content_code         VARCHAR(16) NOT NULL DEFAULT 'TEXT',   -- TEXT | IMAGE (solo aplica a USER)
    media_url            TEXT,                                  -- URL Cloudinary si content_code=IMAGE
-- Idempotencia de cliente (evita duplicados si reintenta)
    client_dedup_key     UUID,
    -- Auditoría
    created_by           INT NOT NULL,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now()
    );

-- Orden/paginación por cotización
CREATE INDEX IF NOT EXISTS ix_chat_quote
    ON deals.chat_message(quote_id, chat_message_id);

-- Idempotencia por cliente (si se envía la clave)
CREATE UNIQUE INDEX IF NOT EXISTS ux_chat_msg_dedup
    ON deals.chat_message (quote_id, client_dedup_key)
    WHERE client_dedup_key IS NOT NULL;

-- Evitar duplicar eventos de sistema ligados a cambios/aceptación
CREATE UNIQUE INDEX IF NOT EXISTS ux_chat_msg_sys_change
    ON deals.chat_message (quote_id, system_subtype_code, ref_change_id)
    WHERE type_code='SYSTEM' AND ref_change_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_chat_msg_sys_accept
    ON deals.chat_message (quote_id, system_subtype_code, ref_acceptance_id)
    WHERE type_code='SYSTEM' AND ref_acceptance_id IS NOT NULL;

-- Reglas de consistencia (CHECKs simples)
ALTER TABLE deals.chat_message
    ADD CONSTRAINT ck_chat_message_content
        CHECK (content_code IN ('TEXT','IMAGE'));

-- Si es USER+IMAGE, debe tener media_url; si es SYSTEM, system_subtype_code debe venir
ALTER TABLE deals.chat_message
    ADD CONSTRAINT ck_chat_message_required_fields
        CHECK (
            (type_code='USER' AND (
                (content_code='TEXT'  AND media_url IS NULL) OR
                (content_code='IMAGE' AND media_url IS NOT NULL)
                ))
                OR
            (type_code='SYSTEM' AND system_subtype_code IS NOT NULL)
            );

CREATE TABLE IF NOT EXISTS deals.chat_read (
                                               quote_id              INT NOT NULL REFERENCES deals.quote(quote_id) ON DELETE CASCADE,
    user_id               INT NOT NULL,
    last_seen_message_id  INT NOT NULL DEFAULT 0,
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (quote_id, user_id)
    );

CREATE INDEX IF NOT EXISTS ix_chat_read_user
    ON deals.chat_read(user_id);

-- Miembros del chat por cotización (snapshot mínima)
CREATE TABLE IF NOT EXISTS deals.chat_participant (
                                                      quote_id   INT NOT NULL REFERENCES deals.quote(quote_id) ON DELETE CASCADE,
    user_id    INT NOT NULL,
    joined_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (quote_id, user_id)
    );

-- Para listar “mis chats”
CREATE INDEX IF NOT EXISTS ix_chat_participant_user
    ON deals.chat_participant(user_id);

-- =========================================
-- ASSIGNMENT (conductor/vehículo) 0..1 activa por cotización (sin historial ahora)
-- =========================================
CREATE TABLE IF NOT EXISTS deals.assignment (
                                                assignment_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                quote_id      INT NOT NULL UNIQUE REFERENCES deals.quote(quote_id) ON DELETE CASCADE,
    driver_id     INT NOT NULL,         -- FK a fleet.drivers(id) si aplica
    vehicle_id    INT NOT NULL,         -- FK a fleet.vehicles(id)
    assigned_by   INT NOT NULL,
    assigned_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    version       INT NOT NULL DEFAULT 0
    );

-- =========================================
-- PAYMENTS (ligero: snapshot de monto + estado)
-- =========================================
CREATE TABLE IF NOT EXISTS deals.payment (
                                             payment_id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             quote_id        INT NOT NULL UNIQUE REFERENCES deals.quote(quote_id) ON DELETE CASCADE,
    amount          NUMERIC(18,2) NOT NULL CHECK (amount >= 0),  -- autocompletado desde la cotización
    currency_code   VARCHAR(3) NOT NULL DEFAULT 'PEN',
    reference       VARCHAR(64),                        -- NULL permitido
    status_code     VARCHAR(16) NOT NULL REFERENCES deals.catalog_payment_status(code) DEFAULT 'MADE',
    made_by         INT NOT NULL,
    made_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    confirmed_by    INT,
    confirmed_at    TIMESTAMPTZ,
    idempotency_key VARCHAR(64) UNIQUE,
    version         INT NOT NULL DEFAULT 0
    );

-- =========================================
-- CHECKLIST: plantilla + instancia (sin data_schema ni JSON)
-- =========================================
CREATE TABLE IF NOT EXISTS deals.checklist_template (
                                                        template_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                        name        TEXT NOT NULL,
                                                        is_default  BOOLEAN NOT NULL DEFAULT TRUE,
                                                        active      BOOLEAN NOT NULL DEFAULT TRUE,
                                                        created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
    );

CREATE TABLE IF NOT EXISTS deals.checklist_template_item (
                                                             template_item_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                             template_id      INT NOT NULL REFERENCES deals.checklist_template(template_id) ON DELETE CASCADE,
    code             VARCHAR(64) NOT NULL,              -- DOC_GRE_REMITENTE | DOC_GRE_TRANSPORTISTA | PAYMENT_MADE | ...
    name             TEXT NOT NULL,
    actor_code       VARCHAR(16) NOT NULL REFERENCES deals.catalog_actor_role(code),
    kind_code        VARCHAR(16) NOT NULL REFERENCES deals.catalog_checklist_kind(code),
    required         BOOLEAN NOT NULL DEFAULT TRUE,
    UNIQUE(template_id, code)
    );

CREATE TABLE IF NOT EXISTS deals.checklist_template_dependency (
                                                                   template_id      INT NOT NULL,
                                                                   item_code        VARCHAR(64) NOT NULL,
    depends_on_code  VARCHAR(64) NOT NULL,
    PRIMARY KEY (template_id, item_code, depends_on_code),
    FOREIGN KEY (template_id, item_code)
    REFERENCES deals.checklist_template_item(template_id, code) ON DELETE CASCADE,
    FOREIGN KEY (template_id, depends_on_code)
    REFERENCES deals.checklist_template_item(template_id, code) ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS deals.checklist_instance (
    instance_id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quote_id     INT NOT NULL UNIQUE REFERENCES deals.quote(quote_id) ON DELETE CASCADE,
    template_id  INT NOT NULL REFERENCES deals.checklist_template(template_id),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
    );

CREATE TABLE IF NOT EXISTS deals.checklist_instance_item (
    instance_item_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instance_id      INT NOT NULL REFERENCES deals.checklist_instance(instance_id) ON DELETE CASCADE,
    code             VARCHAR(64) NOT NULL,      -- copia del code del template
    status_code      VARCHAR(16) NOT NULL REFERENCES deals.catalog_checklist_status(code) DEFAULT 'PENDING',
    completed_by     INT,
    completed_at     TIMESTAMPTZ,
    -- referencias tipadas (INT):
    document_id      INT,                        -- id del GRE en su BC
    payment_id       INT REFERENCES deals.payment(payment_id),
    assignment_id    INT REFERENCES deals.assignment(assignment_id),
    UNIQUE(instance_id, code)
    );
CREATE INDEX IF NOT EXISTS ix_checkitem_instance ON deals.checklist_instance_item(instance_id, status_code);

-- =========================================
-- OUTBOX (opcional hoy; fiabilidad de push para WS)
-- =========================================
CREATE TABLE IF NOT EXISTS deals.outbox (
    event_id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_kind    VARCHAR(32) NOT NULL,     -- 'request-pending' | 'quote-chat' | 'user-notification' (futuro)
    request_id    INT,                      -- si route_kind = 'request-pending'
    quote_id      INT,                      -- si route_kind = 'quote-chat'
    event_type    VARCHAR(64) NOT NULL,     -- QUOTE_CREATED | CHECKLIST_ITEM_DONE | ...
    payload       JSONB NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    processed_at  TIMESTAMPTZ
    );
CREATE INDEX IF NOT EXISTS ix_outbox_unprocessed
    ON deals.outbox(processed_at) WHERE processed_at IS NULL;

-- =========================================
-- IDEMPOTENCIA (acciones sensibles)
-- =========================================
CREATE TABLE IF NOT EXISTS deals.decision_log (
    decision_id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key VARCHAR(64) NOT NULL UNIQUE,
    quote_id        INT,
    action_code     VARCHAR(32) NOT NULL,   -- ACCEPTANCE_START | ACCEPTANCE_CONFIRM | PROPOSE_CHANGE | ...
    result_code     VARCHAR(32),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
    );
