-- Schema for Fleet BC
CREATE SCHEMA IF NOT EXISTS fleet;

-- Vehicles
CREATE TABLE IF NOT EXISTS fleet.vehicles (
  vehicle_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id   INTEGER     NOT NULL,
  name         VARCHAR(120) NOT NULL,
  plate        VARCHAR(16)  NOT NULL,
  active       BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
  CONSTRAINT uq_vehicles_company_plate UNIQUE (company_id, plate)
);

CREATE INDEX IF NOT EXISTS ix_vehicles_company ON fleet.vehicles(company_id);

-- Drivers
CREATE TABLE IF NOT EXISTS fleet.drivers (
  driver_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id     INTEGER     NOT NULL,
  first_name     VARCHAR(120) NOT NULL,
  last_name      VARCHAR(120) NOT NULL,
  email          VARCHAR(200),
  phone          VARCHAR(50),
  license_number VARCHAR(32),
  active         BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
  CONSTRAINT uq_drivers_company_license UNIQUE (company_id, license_number)
);

CREATE INDEX IF NOT EXISTS ix_drivers_company ON fleet.drivers(company_id);


